/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
        "./resources/**/*.css",
        "./storage/framework/views/*.php",
        "node_modules/preline/dist/*.js",
    ],
    safelist: [
        'w-48',
        'w-64',
        'list-disc',
        'list-decimal',
        'list-square',
        'list-circle',
        'list-lower-alpha',
        'list-lower-roman',
        'list-upper-alpha',
        'list-upper-roman',
        'text-gray-600',
        'from-blue-400',
        'to-blue-600',
        'from-green-400',
        'to-green-600',
        'from-yellow-400',
        'to-yellow-600',
        'from-gray-400',
        'to-gray-600',
        'size-16',
        'bg-blue-500',
        'bg-green-500',
        'bg-yellow-500',
        'bg-red-500',
        'marker:text-blue-600',
        'bg-yellow-500',
        'xxxxx',
        'flex-wrap',
        'inset-x-0',
        'top-0',
        'sticky',
        'text-red-600',
        'text-blue-600',
        'text-green-600',
        'text-purple-600',
        'text-gray-600',
        'text-pink-600',
        'text-yellow-600',
        'text-indigo-600',
        'text-teal-600',
        'text-orange-600',
        'text-lime-600',
        'text-amber-600',
        'text-emerald-600',
        'text-cyan-600',
        'text-rose-600',
        'text-fuchsia-600',
        'text-violet-600',
        'text-sky-600',
        'text-stone-600',
        'text-zinc-600',
        'text-neutral-600',
        'text-slate-600',
        'xxxxxx',
        'border-red-600',
        'border-blue-600',
        'border-green-600',
        'border-purple-600',
        'border-gray-600',
        'border-pink-600',
        'border-yellow-600',
        'border-indigo-600',
        'border-teal-600',
        'border-orange-600',
        'border-lime-600',
        'border-amber-600',
        'border-emerald-600',
        'border-cyan-600',
        'border-rose-600',
        'border-fuchsia-600',
        'border-violet-600',
        'border-sky-600',
        'border-stone-600',
        'border-zinc-600',
        'border-neutral-600',
        'border-slate-600',
        'xxxxxx',
        'bg-red-50',
        'bg-blue-50',
        'bg-green-50',
        'bg-purple-50',
        'bg-gray-50',
        'bg-pink-50',
        'bg-yellow-50',
        'bg-indigo-50',
        'bg-teal-50',
        'bg-orange-50',
        'bg-lime-50',
        'bg-amber-50',
        'bg-emerald-50',
        'bg-cyan-50',
        'bg-rose-50',
        'bg-fuchsia-50',
        'bg-violet-50',
        'bg-sky-50',
        'bg-stone-50',
        'bg-zinc-50',
        'bg-neutral-50',
        'bg-slate-50',
    ],
    theme: {
        fontFamily: {
            sans: ['Inter', 'Helvetica', 'sans-serif'],
        },
        extend: {
            utilities: {
                '.word-break-all': {
                    'word-break': 'break-word',
                    'overflow-wrap': 'break-word'
                },
                '.scrollbar-code': {
                    '&::-webkit-scrollbar': {
                        height: '8px',
                    },
                    '&::-webkit-scrollbar-thumb': {
                        backgroundColor: 'rgba(156, 163, 175, 0.5)',
                        borderRadius: '4px',
                    },
                },
                '.break-long-words': {
                    'word-break': 'break-word',
                    'overflow-wrap': 'break-word',
                    'hyphens': 'auto',
                },
            },
            colors: {
                // 'dark-text': '#353f55',
                // 'neutral-900': '#131B28',
            },
            listStyleType: {
                none: 'none',
                disc: 'disc',
                decimal: 'decimal',
                square: 'square',
                circle: 'circle',
                'lower-alpha': 'lower-alpha',
                'lower-roman': 'lower-roman',
                'upper-alpha': 'upper-alpha',
                'upper-roman': 'upper-roman',
            }
        }
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
        require('tailwindcss-animated'),
        require('preline/plugin'),
    ],
}
