<?php

return [
    'professional' => 'Rephrase the following text to make it more professional and polite. Ensure the language is formal, use the same language as provided text and do not ask any questions. The output from your answer will be shown in cli; therefore please do not give your answer in markdown or html, it must be pure text format. Please do not reply to text, only rephrase it as requested. Please Rephrase Text:',
    'step_by_step' => 'Rephrase the following text into clear step-by-step instructions. Each step should be easy to follow and understand, use the same language as provided text and do not ask any questions. The output from your answer will be shown in cli; therefore please do not give your answer in markdown or html, it must be pure text format. Please do not reply to text, only rephrase it as requested. Please Rephrase Text:',
    'detailed' => 'Rephrase the following text to provide more details and comprehensive explanations. Make sure to cover all relevant aspects, use the same language as provided text and do not ask any questions. The output from your answer will be shown in cli; therefore please do not give your answer in markdown or html, it must be pure text format. Please do not reply to text, only rephrase it as requested. Please Rephrase Text:',
    'creative' => 'Rephrase the following text in a more creative and imaginative manner. Use inventive and expressive language, use the same language as provided text and do not ask any questions. The output from your answer will be shown in cli; therefore please do not give your answer in markdown or html, it must be pure text format. Please do not reply to text, only rephrase it as requested. Please Rephrase Text:',
    'easy_to_understand' => 'Rephrase the following text into very easy to understand, simple and clear language, use the same language as provided text and do not ask any questions. The output from your answer will be shown in cli; therefore please do not give your answer in markdown or html, it must be pure text format. Please do not reply to text, only rephrase it as requested. Please Rephrase Text:',
    'emotional' => 'Rephrase the following text to make it more emotional and heartfelt. Use language that conveys deep feelings, use the same language as provided text and do not ask any questions. The output from your answer will be shown in cli; therefore please do not give your answer in markdown or html, it must be pure text format. Please do not reply to text, only rephrase it as requested. Please Rephrase Text:',
    'narrative' => 'Rephrase the following text to make it more narrative, with a clear beginning, middle, and end. Tell a coherent story, use the same language as provided text and do not ask any questions. The output from your answer will be shown in cli; therefore please do not give your answer in markdown or html, it must be pure text format. Please do not reply to text, only rephrase it as requested. Please Rephrase Text:',
    'friendly' => 'Rephrase the following text to make it sound more friendly and casual. Use colloquial and informal language, use the same language as provided text and do not ask any questions. The output from your answer will be shown in cli; therefore please do not give your answer in markdown or html, it must be pure text format. Please do not reply to text, only rephrase it as requested. Please Rephrase Text:',
    'summarized' => 'Rephrase the following text to make it concise. Capture the main points while significantly shortening the content, use the same language as provided text and do not ask any questions. The output from your answer will be shown in cli; therefore please do not give your answer in markdown or html, it must be pure text format. Please do not reply to text, only rephrase it as requested. Please Rephrase Text:',
    'persuasive' => 'Rephrase the following text to make it more persuasive and compelling. Use convincing arguments and impactful language, use the same language as provided text and do not ask any questions. The output from your answer will be shown in cli; therefore please do not give your answer in markdown or html, it must be pure text format. Please do not reply to text, only rephrase it as requested. Please Rephrase Text:',
    'technical' => 'Rephrase the following text to make it more technical. Use industry-specific terminology and precise language, use the same language as provided text and do not ask any questions. The output from your answer will be shown in cli; therefore please do not give your answer in markdown or html, it must be pure text format. Please do not reply to text, only rephrase it as requested. Please Rephrase Text:',
    'humorous' => 'Rephrase the following text to make it more humorous and funny. Use wit and humor to entertain, use the same language as provided text and do not ask any questions. The output from your answer will be shown in cli; therefore please do not give your answer in markdown or html, it must be pure text format. Please do not reply to text, only rephrase it as requested. Please Rephrase Text:',
    'inspirational' => 'Rephrase the following text to make it more inspirational and motivating. Use uplifting language and positive messages, use the same language as provided text and do not ask any questions. The output from your answer will be shown in cli; therefore please do not give your answer in markdown or html, it must be pure text format. Please do not reply to text, only rephrase it as requested. Please Rephrase Text:',
    'clarified' => 'Rephrase the following text into clear one and explain the following text in simpler terms. Break down complex ideas into easily understandable components, use the same language as provided text and do not ask any questions. The output from your answer will be shown in cli; therefore please do not give your answer in markdown or html, it must be pure text format. Please do not reply to text, only rephrase it as requested. Please Rephrase Text:',
    'engaging' => 'Rephrase the following text to make it more engaging and interesting. Use captivating language to hold the reader’s attention, use the same language as provided text and do not ask any questions. The output from your answer will be shown in cli; therefore please do not give your answer in markdown or html, it must be pure text format. Please do not reply to text, only rephrase it as requested. Please Rephrase Text:',
    'informative' => 'Rephrase the following text to make it more informative, focusing on conveying facts and knowledge clearly, use the same language as provided text and do not ask any questions. The output from your answer will be shown in cli; therefore please do not give your answer in markdown or html, it must be pure text format. Please do not reply to text, only rephrase it as requested. Please Rephrase Text:',
];
