name: Build App for Mac

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
          extensions: sqlite3, pdo_sqlite, fileinfo, mbstring, tokenizer, xml, ctype, json, pdo, openssl

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Create SQLite Database File
        run: touch database/database.sqlite

      - name: Install dependencies
        run: composer install --optimize-autoloader --no-dev

      - name: Set up Laravel Environment
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --force

      - name: Install NativePHP
        run: |
          php artisan native:install --no-interaction
          npm install --no-audit --no-fund --loglevel=error

      - name: Build NativePHP App on macOS
        run: php artisan native:build mac x86 --no-interaction

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nativephp-app
          path: dist/
