name: Build App for Windows & Mac

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: fileinfo, mbstring, tokenizer, xml, ctype, json, pdo, sqlite3, openssl

      - name: Install dependencies
        run: composer install --optimize-autoloader --no-dev

      - name: Create SQLite Database File
        run: touch database/database.sqlite

      - name: Set up .env Database
        run: |
          php artisan key:generate
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            powershell -Command "(gc .env) -replace 'DB_CONNECTION=mysql', 'DB_CONNECTION=sqlite' | Set-Content .env"
            powershell -Command "(gc .env) -replace 'DB_DATABASE=.*', 'DB_DATABASE=database/database.sqlite' | Set-Content .env"
          else
            sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/' .env
            sed -i 's/DB_DATABASE=.*/DB_DATABASE=database\/database.sqlite/' .env
          fi

      - name: Run migrations
        run: php artisan migrate --force

      - name: Build NativePHP App
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            nativephp build --win;
          else
            nativephp build --mac;
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nativephp-app
          path: dist/
